### ISSUE TITLE
Bars only work for 5 seconds

### ISSUE THREAD

**Issue by lrhorer** [VixenLights/Vixen#149]
I have not tried every possible setup for bars, but on at least 3 different profiles (move up, move down, move left to right) the bars effect only works properly for about 5 seconds.  During the first five seconds, the bars move properly and smoothly.  Then they freeze in place and start jittering.  I have not had the chance to observe the effect in the physical display, but this is what shows up in the preview, and would expect it to look much the same in the display.  I will try to confirm on Monday.

**Comment by jeffu231** [comment]
I tried to add one to a new sequence in your profile and it looks to work as expected. Can you create a test sequence with this issue that I can download and reproduce it. I would just need the sequence being as I have your profile now.

**Comment by lrhorer** [comment]
Hmm.  It's not doing it, now.  I swear to you last night it wasn't working properly.  Geez.  I'm really batting zero, here.  You must thinl me quite the idiot.

**Comment by jeffu231** [comment]
No worries. If you come across it again feel free to reach out. One more thing I noticed with the profile is you had a large amount of unused channels allocated in the Vixen controllers. That takes up a lot of resources from the system if they are not being used. When you export to FPP, all those empty channels get exported as well which just wastes file space. The best practice would be to allocate the universes in Vixen as you need them. Hope that helps. Enjoy the holidays and have a happy new year.

**Comment by lrhorer** [comment]
I hear you.  Right now, things are still in flux, so I don't want to do a lot of shuffling.  Once the displays are set in stone, I will compact the addresses so there are no gaps and truncate each controller's universe space.  With the new compression feature (which I love!), the files compres all the way down from 300M - 500M to well under 10M, and the SSD I am using for the show holds 30G.  The array where I store the Vixen profiles holds 48TB, with 18TB free.  I am definitely not concerned about file space.  :-)

I have no doubt the export, in particular, will run far, far faster when I truncate the universes by more than 70%.
